In [1]:
import numpy as np

In [2]:
arr1=np.array([10,20,30,40])
arr=np.array([1,2,3,4])

In [3]:
array_sum=arr1+arr

In [4]:
array_sum

array([11, 22, 33, 44])

In [5]:
import pandas as pd

In [6]:
data= {
    'name':['Alice','akchhat'],
    'age':[5,21]
}

In [7]:
df=pd.DataFrame(data)

In [8]:
df


name  age
0    Alice    5
1  akchhat   21

In [9]:
array1=np.zeros((2,3))

In [10]:
array1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array2=np.linspace(0,5,10)

In [12]:
array2

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [13]:
array3=np.ones((3,3))

In [14]:
array3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
array3.shape

(3, 3)

In [16]:
array3.ndim

2

In [17]:
array3.dtype

dtype('float64')

In [18]:
array3.size

9

In [19]:
array4=np.arange(6)

In [20]:
array4

array([0, 1, 2, 3, 4, 5])

In [21]:
reshaped_array=array4.reshape(2,3)

In [22]:
array4.T

array([0, 1, 2, 3, 4, 5])

In [23]:
reshaped_array.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [24]:
np.random.seed(42)

In [25]:
random_arr=np.random.rand(3,3)

In [26]:
random_arr

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [27]:
y=np.random.randint(1,9)

In [28]:
y

8

In [29]:
arrnew=np.array([5,10,15,20,25])

In [30]:
arrnew*2

array([10, 20, 30, 40, 50])

In [31]:
arrnew[arrnew>10]=99
        

In [32]:
arrnew

array([ 5, 10, 99, 99, 99])

In [33]:
arrl=[a for a in range(1,10)]

In [34]:
arrx=np.array(arrl)

In [35]:
arrx

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arrx[arrx%2!=0]=-1

In [48]:
arrx

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [38]:
arre=[a for a in range(0,10) if a%2==0]

In [39]:
arre

[0, 2, 4, 6, 8]

In [40]:
divby9=[x for x in range(100) if x%9==0]

In [41]:
divby9

[0, 9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99]

In [42]:
divby9arr=np.array(divby9)

In [43]:
divby9arr

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [44]:
dict1={
    "name":["fahad","maher","manjar","mazen"],
    "age":[20,1,34,0.1]
}

In [45]:
df2=pd.DataFrame(dict1)

In [46]:
df2

name   age
0   fahad  20.0
1   maher   1.0
2  manjar  34.0
3   mazen   0.1